name             "site-gittypo3org"
maintainer       "Steffen Gebert / TYPO3 Association"
maintainer_email "steffen.gebert@typo3.org"
license          "Apache 2.0"
description      "Installs/configures git.typo3.org"
version          "0.1.6"

depends "ssl_certificates"
depends "t3-chef-vault"
depends "gitweb"
depends "git-daemon"
depends "apt"
depends "runit"
